title:              Hunting metal ions within cryo-EM derived RNA structures
email:              bussi@sissa.it
description:        Website for the project Hunting metal ions within cryo-EM derived RNA structures
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://bussilab.github.io"

# Social Profiles
twitter_username:   bussilab

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
